### ISSUE TITLE
Manually mark auto_update as false

### ISSUE THREAD

**Issue by Enzime** [buo/homebrew-cask-upgrade#107]
Some programs like Firefox allow you to configure whether or not they auto update, and by disabling this I would like `homebrew-cask-upgrade` to take over with managing the latest version. By allowing users to mark `auto_update` as `false` this would mean that a full upgrade could be done without using `-a` meaning that other apps which actually automatically update won't get updated by `homebrew-cask-upgrade`.

**Comment by Enzime** [comment]
The reason why this flag would be useful on a per application basis is because `-a` attempts to update all apps however some apps don't support disabling `auto_update` and would rather not unnecessarily update them. So if I could mark the ones where I had disabled their inbuilt auto updating mechanism then it'd be nice to be able to update them without specifying `-a`.

**Comment by muescha** [comment]
i think this is it possible with `brew cu firefox -a`?

**Comment by ondrejfuhrer** [comment]
@Enzime exactly as @muescha suggested. I don't think we will implement any super special behaviour here, since this is how it was designed.
