### ISSUE TITLE
Are you aware that `brew cask upgrade` exists?

### ISSUE THREAD

**Issue by vitorgalvao** [buo/homebrew-cask-upgrade#115]
You say in the README (emphasis mine):

> Homebrew Cask extends [Homebrew](http://brew.sh) and brings its elegance, simplicity, and speed to the installation and management of GUI macOS applications and large binaries alike, **but it lacks a sub-command like `brew upgrade` to upgrade installed apps, so if you want to upgrade the installed apps, you have to delete the previous versions and re-install the latest version manually for every single app.**

Are you aware that `brew cask upgrade` has been live and working for months?

**Comment by ran-dall** [comment]
You can also update all apps that are "auto update enabled" and using "latest" version tag using `brew cask upgrade --greedy`

**Comment by ondrejfuhrer** [comment]
@vitorgalvao Yes we are aware and we were already discussing it with 
@reitermarkus in https://github.com/buo/homebrew-cask-upgrade/issues/95 

The readme is definitely outdated, there I have to agree. This extension of `brew cask upgrade` brings some visual changes and also some capabilities that we like 🙂 (i.e. it is interactive, where all commands in brew are meant to be non-interactive, we can choose which apps to update and which not, also it they have auto-update, are of "latest" type, etc.)

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/buo/homebrew-cask-upgrade/pull/118.
