### ISSUE TITLE
Add support for cask's --no-quarantine argument

### ISSUE THREAD

**Issue by jesteron** [buo/homebrew-cask-upgrade#124]
Hi,

would be great if you could add support for cask's --no-quarantine argument, which prevents cask from setting the com.apple.quarantine extended attribute. 

E.g. _brew cu -q_ could be used to install all updates without setting the quarantine attribute.
I would really prefer this solution instead over removing the attribute manually after each update.

**Comment by ashishb** [comment]
Any updates on this?
It took me a while to [figure](https://ashishb.net/tech/mac-os-app-translocation-and-android-studio-updates-failure/) out the root cause as well.

**Comment by ondrejfuhrer** [comment]
Hey @jesteron , that support has been already added a month ago in https://github.com/buo/homebrew-cask-upgrade/commit/8592134f24cb52374554e9f447a46d09b7f5ca47 

There is no "short" argument, you just have to use `brew cu --no-quarantine` and it should work fine. Please let us know if it works fine for you and if so, close this issue.

**Comment by jesteron** [comment]
Hey @ondrejfuhrer, work like a charm. Thanks for your support!
