### ISSUE TITLE
Support for simultaneous multiple apps

### ISSUE THREAD

**Issue by Wdavery** [buo/homebrew-cask-upgrade#126]
It would be nice to be able to run updates on multiple specific apps such as is available in the main Homebrew:
`brew cask upgrade app1 app2 app3`

Currently the following command only runs on 'app1'
`brew cu -a app1 app2 app3`

**Comment by ondrejfuhrer** [comment]
Hey @Wdavery thanks for this! I actually never noticed that it is not supported 🙂 PR created now only waiting for @buo to approve and merge 🙂
