### ISSUE TITLE
Move this as a "company" repository?

### ISSUE THREAD

**Issue by ondrejfuhrer** [buo/homebrew-cask-upgrade#131]
Hey @buo ,

I was wondering, if you haven't thought about creating a "company" account for this tap and move it there so you can easily add members, that could help you with maintaining? I noticed that you don't have much time reviewing issues here, etc. so that could be helpful for you, no?

Or, of course, you can give write access to some "trustworthy" contributors? I also don't have super much time, but this is a low-maintenance repository, where I could help you?

Also if there are any other people here that would like to help maintaining this, feel free to speak up 🙂  

Happy Christmas time from Germany! 🎄🌟🎅🎁🎄

**Comment by ondrejfuhrer** [comment]
Thank you, @buo 🙂 👍

**Comment by buo** [comment]
You’re very much welcomed. I appreciate your contributions! thank you 😊
