### ISSUE TITLE
[FR] Don't downgrade flag

### ISSUE THREAD

**Issue by yurikoles** [buo/homebrew-cask-upgrade#133]
I had just [bumped](https://github.com/Homebrew/homebrew-cask-versions/pull/6962) `telegram-desktop-dev` with `cask-repair` and when I run `brew cu --all --yes` I see:
```
[...]
==> Found outdated apps
[...]
2/2  telegram-desktop-dev       1.5.12   1.5.11   Y   [ FORCED ]
```

**Comment by mkll** [comment]
@yurikoles Try to use `-f`

**Comment by yurikoles** [comment]
@mkll 
```
    -f  --force           Include apps that are marked as latest
                          (i.e. force-reinstall them).
```
I don't want that

**Comment by mkll** [comment]
Obviously, I misunderstood what you need.

**Comment by muescha** [comment]
the new version should not be included in the "outdated app" section

PS: i understand your issue right?

**Comment by ondrejfuhrer** [comment]
Hey @yurikoles , thanks for the suggestion, but not sure if that is easily possible. It would probably work fine if the version would be in some "1.1.1" format. But i.e. java has a version `8u202,b08:1961070e4c9b4e26a04e7f5a083f551e` and there would need to be some sort of custom per cask comparator, where you can decide if it is greater or not. 

I don't think that is going to change anytime soon and the "problem" you are describing here is just for a small number of people (that are cask contributors), not really work for anyone else. 

Or do you see any other use case I'm missing here?

**Comment by yurikoles** [comment]
@ondrejfuhrer, yes you are right, it seems to break other apps.

**Comment by muescha** [comment]
maybe as a workaround it is possible to exclude it (until the cask formula is submitted to cask repo) with the `pin version` command?
