### ISSUE TITLE
Interface improvements suggestion

### ISSUE THREAD

**Issue by mathbunnyru** [buo/homebrew-cask-upgrade#14]
First of all, I suggest to use two-digit (or three) numbers while listing installed apps (it's easier to read when everything is aligned. So it will become 05/75 instead of 5/75)

Second thing I suggest is text coloring - it seems to be that the phrase 'up to date' should be green, old version is red and a new version is green too. It makes text easier to read.

**Comment by atais** [comment]
+1 for text coloring
