### ISSUE TITLE
Some applications display the latest version incorrectly

### ISSUE THREAD

**Issue by liby** [buo/homebrew-cask-upgrade#151]
- As shown below, an update is prompted within the application, but the CLI still shows the current version as the latest.
![WeChat](https://user-images.githubusercontent.com/38807139/74906779-ece46600-53ec-11ea-9f02-34a4262f3479.jpg)

- I don't know if this is an issue with "homebrew-cask-upgrade" or if some applications are not uploading the latest version to the website

- By the way, what does "A / U" mean? I don't see the relevant documentation.
    - Is it an auto-update? 
    - If "Y" is displayed, the application will ask you if you want to upgrade while the application is running.
- Am I getting this right?

**Comment by ondrejfuhrer** [comment]
Hello @liby , thank you for letting us know. The version update is a manual process in [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) repo, therefore it is updated hours (sometimes days) after the new version is released. Is it not something we can do here 🙂 

Regarding the `A / U` column, that means Auto-Update and indicates if that application has auto-update capabilities. You can also see the `[  PASS  ]` result on those apps -> if you would like to update them, you need to add `-a` or `--all` parameter to the command (`brew cu -a`).

Hope that answers your questions 🙂

**Comment by liby** [comment]
Thank you for your concise, understandable and timely reply.

One last question before we close. I hope you can answer me.

The user himself clicks the upgrade within the application, can [homebrew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade) gets the version number of the program after it has been updated, and it shows up in `[ Pass ]` result.

Have you considered supporting this feature?

**Comment by ondrejfuhrer** [comment]
Unfortunately that is not possible since the app would need to provide Homebrew with that information. I don't know about a way of detecting that change. There were discussions about that before in the Homebrew community and AFAIK there was no solution to this problem.
