### ISSUE TITLE
Version of apps are mismatched

### ISSUE THREAD

**Issue by Parthvsquare** [buo/homebrew-cask-upgrade#166]
Here is an example of lastpass
![image](https://user-images.githubusercontent.com/26404957/86453141-eec71a00-bd3a-11ea-90b2-df1ae3a91fbe.png)
i did not use brew cu to update as i was prompted to from auto update. is this what causing the error

**Comment by ondrejfuhrer** [comment]
Hello @Parthvsquare , please read the not about auto-updates here: https://github.com/buo/homebrew-cask-upgrade#apps-with-auto-update
