### ISSUE TITLE
Error: cannot load such file -- cask/all

### ISSUE THREAD

**Issue by Sgryt87** [buo/homebrew-cask-upgrade#170]
I'm currently facing an issue upgrading outdated apps:

`➜  ~ brew cu
Error: cannot load such file -- cask/all
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:5:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:67:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:83:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:114:in `<main>'`

`➜  ~ brew info cu
Error: No available formula with the name "cu"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.`

Brew version:
`  ~ brew --version
Homebrew 2.4.9-336-g264de96
Homebrew/homebrew-core (git revision 6eb30f; last commit 2020-08-09)
Homebrew/homebrew-cask (git revision 2803f4; last commit 2020-08-10)`

Despite `brew cu --help` outputs the `cu` commands: 

`➜  ~ brew cu --help

USAGE brew cu [command=run] [CASK] [options]

 cu [options]
    Upgrade every outdated app installed by brew cask.`

**Comment by rahularora** [comment]
+1 Seeing the same issue

**Comment by LeerGo** [comment]
see here #169 @rahularora @Sgryt87

**Comment by amharris** [comment]
Also experiencing the same issue.

I can individually run `brew cask upgrade <cask_formula>` but not `brew cu` or `brew cu -a` fail with the error reported above.

**Comment by ondrejfuhrer** [comment]
Fixed by https://github.com/buo/homebrew-cask-upgrade/pull/168
