### ISSUE TITLE
`--no-quarantine` flag not working anymore

### ISSUE THREAD

**Issue by F30** [buo/homebrew-cask-upgrade#178]
When `brew cu` is called with the `--no-quarantine` argument, app installations now fail with:

```
Usage: brew reinstall [options] formula

…

Error: invalid option: --no-quarantine
```

I suppose this is because of the change to `brew reinstall` instead of `brew cask reinstall`.

**Comment by ondrejfuhrer** [comment]
Hey @F30 , I did double check this and it seems it's working again. Therefore I'm closing this issue, feel free to create a new one if the issue occurs again.
