### ISSUE TITLE
Wrong warning

### ISSUE THREAD

**Issue by ucayalifish** [buo/homebrew-cask-upgrade#18]
First, thank you for great tool!
One minor complaint though, it issues warning "Warning: The default Caskroom location has moved to /usr/local/Caskroom." even i case of 
`$ echo $HOMEBREW_CASK_OPTS`
`--caskroom=/opt/homebrew-cask/Caskroom`

**Comment by adidalal** [comment]
That's a Caskroom warning.
That warning will show because it is true.
The default location *has* changed to `/usr/local/Caskroom`

See https://github.com/caskroom/homebrew-cask/issues/24609#issuecomment-248134444 for a relatively easy way to move Caskroom locations.

**Comment by ucayalifish** [comment]
Shouldn't `$ echo $HOMEBREW_CASK_OPTS
--caskroom=/opt/homebrew-cask/Caskroom` prevent it? `brew cask` stopped complain as soon as I set this environment var.

**Comment by buo** [comment]
As this is related to Homebrew Cask itself, I will close this issue.
