### ISSUE TITLE
Empty outdated apps results

### ISSUE THREAD

**Issue by adima959** [buo/homebrew-cask-upgrade#181]
Hello,

Thanks for this awesome software! 

I use it on my desktop without any errors, on my laptop, it refuses to work. 

`brew --version
Homebrew 2.7.5
Homebrew/homebrew-core (git revision dfd11; last commit 2021-01-20)
Homebrew/homebrew-cask (git revision b5689; last commit 2021-01-20)`

**If i run:** 
`➜  ~ brew tap
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/core`

`➜  ~ brew cu
==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Already up-to-date.
==> Finding outdated apps
  Cask  Current  Latest  A/U  Result
➜  ~`

I have tried to remove everything, re-install everything. With no help. 

Thanks in advance.

**Comment by ondrejfuhrer** [comment]
Hello @adima959

Might be a silly question, but do you have any casks installed with `brew`? What is the result of `brew list --cask` command?

**Comment by adima959** [comment]
Hey,

Not silly at all! I just realized this after your comment that all apps **must** be installed via brew in order to show up. :) 

Closing this as it is **not** an issue.

**Comment by ondrejfuhrer** [comment]
No worries @adima959 , happens 🙂  Have a great day.
