### ISSUE TITLE
Keep update the some app version !!

### ISSUE THREAD

**Issue by gcpmusic** [buo/homebrew-cask-upgrade#186]
This happen with a few app now. Any thoughts about ?
Thanks

<img width="637" alt="Screenshot 2021-03-27 at 19 40 43" src="https://user-images.githubusercontent.com/32528176/112731148-dab0f180-8f35-11eb-84d5-ee7b4968b799.png">

**Comment by yurikoles** [comment]
In fact, it's not the same version, it just cut, see: https://github.com/Homebrew/homebrew-cask/pull/102768

**Comment by gcpmusic** [comment]
I see. Thank you.
