### ISSUE TITLE
Warning: Calling Hbc::DSL#license is deprecated!

### ISSUE THREAD

**Issue by ssreekanth** [buo/homebrew-cask-upgrade#20]
Thank you for your time in developing this great tool.

It was working fine until yesterday. However, Today when I ran `brew cu`, I got lots of these warnings -

```
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:11:in `block in outdated'
Please report this to the buo/cask-upgrade tap!
```

Any idea what might be causing this?

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/issues/25214
You need to `brew upgrade`

**Comment by ssreekanth** [comment]
`brew upgrade` fixed it for now. But, Homebrew/brew#1241 looks like a temporary fix, as per the comment.

**Comment by adidalal** [comment]
This should no longer be an issue, I believe.

**Comment by ssreekanth** [comment]
@adidalal It would be nice if you could provide more info indicating that the issue is resolved with a proper fix permanently.

**Comment by adidalal** [comment]
We removed that stanza from all Casks, so the error shouldn't pop up.
The above PR will be reverted at some point (soon), but it should (correctly) not throw up any errors.

**Comment by ssreekanth** [comment]
Closing this issue.

**Comment by EmilVarona** [comment]
Sorry to revive an old issue but I run this alias daily

 `alias brewski='brew update && brew upgrade && brew cleanup && brew cask cleanup; brew doctor'`

I noticed this morning that I started getting the following errors on `brew upgrade`

```
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in 'load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:20:in 'block in load'
```
Seeing that I'm running `brew upgrade` each and every time, I'm not sure why I'm getting this message. Any thoughts would be appreciated. FYI: I'm on OSX 10.12.6, fully patched and up to date.

**Comment by adidalal** [comment]
@EmilVarona Please follow the guide at https://github.com/caskroom/homebrew-cask#reporting-bugs

**Comment by EmilVarona** [comment]
@adidalal Thank you. I posted a new issue, #37489.

**Comment by docgyneco69** [comment]
Found the culprit for all the  _**"Warning ...#license..."**_ messages I was getting: an outdated cask, the _(discontinued?)_ beloved **[clipmenu](https://github.com/naotaka/ClipMenu)**. Running **brew cask audit**, cask by cask via a one liner bash loop (cf below should it helps) did the trick for me.
`while IFS= read -r _c _ ; do echo -e "$_c =>" ; brew cask audit "$_c" ; done <<<"$(brew cask list)"`

**Comment by jrking123** [comment]
I just ran the audit loop from @docgyneco69 - in my system's case this error was triggered by emacs-mac. Some serious strangeness "cured" by uninstalling it.

**Comment by jball** [comment]
Thanks for the bash loop @docgyneco69 for me it was java7. Once I removed that it the message went away.

**Comment by pquodling** [comment]
I saw this on an app called sitesucker as well.

**Comment by alecthegeek** [comment]
This is a little simpler to type.

brew cask list 2> /dev/null | xargs -I {} brew cask audit {}

**Comment by alecthegeek** [comment]
Running `brew cask ...` across all my installed packages gave no result. I am still getting

```shell
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:18:in `block in load'
```

**Comment by alecthegeek** [comment]
OK -- turned out I have made my life hard because of the complex way I have my Mac setup. However it turned out that a couple of packages had changed their name (google-drive, flash). So an uninstall and then install with the new name fixed that...

**Comment by mirageglobe** [comment]
yep `google-drive` is the culprit. its been changed to `google-backup-and-sync`

**Comment by garciparedes** [comment]
`robomongo` the problem in my case.

**Comment by von** [comment]
Three casks are giving me this error: handbrake, omnigraffle, and ripit. Uninstall and re-install doesn't help.

**Comment by n8henrie** [comment]
My attempt at a little more readable output and resulting problematic packages:

```shell_session
$ brew cask list 2>/dev/null | gxargs -I{} bash -c 'cask_="{}"; brew cask audit "${cask_}" 2>&1 1>/dev/null | ggrep "Hbc::DSL#license" >/dev/null && echo "License error in cask: ${cask_}"'
License error in cask: audacity
License error in cask: google-drive
License error in cask: google-photos-backup
License error in cask: picasa
License error in cask: textwrangler
```

**Comment by akindo** [comment]
Getting the error on Tomahawk.

**Comment by ondrejfuhrer** [comment]
@akindo Since Tomahawk app has been removed from homebrew-cask (no update for last 2 years, the project is abandoned), you should consider uninstalling it. The cask will never get updated, as well as the app.

**Comment by akindo** [comment]
@ondrejfuhrer Ok, thanks for the information and the good work on Cask! Yeah, hadn't used that app for a year, and was thinking to myself, meeeeh, could delete that cask.

**Comment by michahell** [comment]
culprit in my case: `messenger-for-desktop` which is an old facebook messenger app. Facebook hate ++.
