### ISSUE TITLE
Gatekeeper and updated apps

### ISSUE THREAD

**Issue by theboyler** [buo/homebrew-cask-upgrade#203]
I don't know if this is the right place for the query - it might be an issue with Homebrew itself - so forgive me if it is. 

I installed this a couple of weeks ago, and notice that after updating, every time the app is first opened, gatekeeper catches it and verifies the file, then asks if I want to open it as it was downloaded from the internet. As I have a few scripts which call apps, they now timeout unless I remember to click to close the box pretty quickly. (NB - I've done the terminal command to enable software to be opened from anywhere is the Privacy Prefpane)

So, is there a way to ensure that apps updated via this tool open without quarantining, as they do when updated from within an app itself directly?

**Comment by yurikoles** [comment]
This issue is common for Homebrew Cask, you may want to put a string `export HOMEBREW_CASK_OPTS="--no-quarantine"` in your shell profile. Also, you may reset Gatekeeper quarantine flag for all installed casks by reinstalling all of them by `brew ls --cask | xargs brew reinstall --cask`

**Comment by ondrejfuhrer** [comment]
@theboyler did that solve your issue? Can we close this then?

**Comment by theboyler** [comment]
Yes, thanks!
