### ISSUE TITLE
Adding password to config file for auto-complete

### ISSUE THREAD

**Issue by theboyler** [buo/homebrew-cask-upgrade#207]
So, when I use CU in terminal, some apps require a password to be entered as part of the installation process for updates; this prevents having CU run automatically via Launchd or by an Alfred workflow, say, because the process won't complete without the user intervention, which the user won't know about or be able to complete because they're not using an interactive process like Terminal where they a) know about the need to enter a password and b) have the means to enter it.

Is this something that can be overridden, whereby a password is entered into a local file and used by CU when homebrew prompts for it for app installs?

**Comment by ondrejfuhrer** [comment]
Thx @yurikoles for jumping in. And he is completely right, currently (except making passwordless sudo) there isn't a way for making this possible. Also saving your sudo password in plain text anywhere on your computer isn't probably a good idea as well 🙂
