### ISSUE TITLE
Cask Pinfile

### ISSUE THREAD

**Issue by darthShadow** [buo/homebrew-cask-upgrade#208]
Hi,

Would it be possible to add functionality to both dump all the pinned casks and restore them to/from a file, something similar to the Brewfile?

Thanks for the wonderful tool btw.

**Comment by ondrejfuhrer** [comment]
Hey @darthShadow , thanks for your suggestion, it's actually fairly easy, please check https://github.com/buo/homebrew-cask-upgrade/pull/209 if that fits your needs.

**Comment by darthShadow** [comment]
Yep, that works. Thanks a lot for making the change so quickly.
