### ISSUE TITLE
Trying to pin VirtualBox<7

### ISSUE THREAD

**Issue by amotl** [buo/homebrew-cask-upgrade#218]
Dear Jack,

thanks a stack for conceiving this excellent program. Because Vagrant does not support VirtualBox 7.x yet, I would like to downgrade to VirtualBox 6 and stay on this version.

I've managed to downgrade VirtualBox to 6.1.38 using this recipe:
```shell
cd "$(brew --repo homebrew/cask)"
git checkout aa3c55951
HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall --cask virtualbox
```

```shell
$ VBoxManage --version
6.1.38r153438
```

Then I tried to pin VirtualBox like this:
```shell
brew tap buo/cask-upgrade
brew cu pin virtualbox
```

However when invoking `brew upgrade --cask --greedy`, Homebrew still upgrades to VirtualBox 7 again:
```
$ brew upgrade --cask --greedy --dry-run
==> Would upgrade 2 outdated packages:
little-snitch 4.5.2 -> 5.5
virtualbox 6.1.38,153438 -> 7.0.0,153978
```

I am sure I am doing something wrong. Maybe you can help me out?

With kind regards,
Andreas.

**Comment by ondrejfuhrer** [comment]
Hey @amotl ,

Thanks for your question. As stated in the readme, "our" cask pinning doesn't prevent the upgrade from happening when using the standard brew commands. Therefore if you would like to pin it, then you have to use `brew cu` to upgrade the apps. Hope that makes sense 🙂 Let me know if you have any other questions.

**Comment by amotl** [comment]
Dear Ondřej,

thanks for your quick response, and apologies for not reading the README thoroughly. Running `brew cu` works perfectly, and does not upgrade to VirtualBox 7. Excellent!

Keep up the spirit, and with kind regards,
Andreas.

**Comment by ondrejfuhrer** [comment]
Hey Andreas,

Just FYI: I just noticed that they released virtualbox6 🙂 so I guess you can use that as well (in `homebrew-cask-versions` tap).

**Comment by amotl** [comment]
Hi Ondřej,

that is sweet. Thanks for letting me know!

With kind regards, Andreas.

On 19 October 2022 14:20:35 CEST, "Ondřej Führer" ***@***.***> wrote:
>Hey Andreas,
>
>
>
>Just FYI: I just noticed that they released virtualbox6 🙂 so I guess you can use that as well (in `homebrew-cask-versions` tap).
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/buo/homebrew-cask-upgrade/issues/218#issuecomment-1283923557
>
>You are receiving this because you modified the open/close state.
>
>
>
>Message ID: ***@***.***>
-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.
