### ISSUE TITLE
Cask with same name as formula leads to formula being upgraded/installed instead of cask

### ISSUE THREAD

**Issue by ROpdebee** [buo/homebrew-cask-upgrade#226]
The `docker` cask is an example. Trying to update it through `cu` leads to a warning from brew:
```
Warning: Treating docker as a formula.
```
after which it installs the `docker` formula. `neo4j` is another example.

brew has a `--cask` flag to disambiguate, so a manual update works:
```
brew upgrade --cask docker
```
I presume `cu` isn't passing this flag to `brew` yet.

Versions:
```
Homebrew 3.6.20-167-g7a5f614
Homebrew/homebrew-core (git revision be29dbf85c2; last commit 2023-01-27)
Homebrew/homebrew-cask (git revision a8fb94a787; last commit 2023-01-28)
```

Seems like this was already fixed a few years back (#177) but for some reason it's happening again. The `--cask` flag appears to work properly now though.

**Comment by ondrejfuhrer** [comment]
Yeah, also noticed that, thx for reporting. Fix is on its way.
