### ISSUE TITLE
Error: Failure while executing; `/usr/bin/sudo -E -- /bin/cp -pR

### ISSUE THREAD

**Issue by zeitchef** [buo/homebrew-cask-upgrade#230]
I've been getting this error for a few days on both my machines - when trying to update, seems the old files aren't being purged and the `cp` command is failing. I'm forced then to uninstall and then reinstall apps manually.

Here's the output when trying to upgrade Raycast, for example:

[raycast.txt](https://github.com/buo/homebrew-cask-upgrade/files/11519397/raycast.txt)

**Comment by yurikoles** [comment]
Have you tried updating with a stock brew commands?

**Comment by zeitchef** [comment]
Running `brew reinstall` did produce the same behavior.

**Comment by vipintom** [comment]
Facing the same issue since last couple of weeks. Have to resort to `brew install --cask --force stats` to get any of the casks to be upgraded to the latest version. Any help regarding this will be appreciated

**Comment by ondrejfuhrer** [comment]
> Running `brew reinstall` did produce the same behavior.

If that's a problem with `brew reinstall` , there is unfortunately not much we can do about it here (as that's exactly what we're using to upgrade). I would suggest reporting that in the brew repo.

**Comment by mhanel** [comment]
I have the same problem, but `brew reinstall --cask --force xyz` usually works for me. Still annoying, because it happened for a few apps, and I needed to reinstall all of them.

**Comment by ondrejfuhrer** [comment]
I'll close this for now as there is not really much we can do.
