### ISSUE TITLE
How to relink cask packages after accidentally upgrading them outside of Homebrew?

### ISSUE THREAD

**Issue by jochne** [buo/homebrew-cask-upgrade#234]
Sometimes, when updating software within the application itself, it is easy to accidentally click on the update button. However, the next time you use Homebrew to manage the software, these cask packages may not be recognized as already installed.

**Comment by jochne** [comment]
thanks for your reply. btw, do you have any recommendation for the tool you
mentioned to reinstall and update the casks?

Ondřej Führer ***@***.***>于2023年7月12日 周三上午4:01写道：

**Comment by ondrejfuhrer** [comment]
Hey @jochne , I meant using `brew cu` (this repo) to use it to upgrade. So even though it will "just" reinstall the same version, that's practically the only way of fixing it.
