### ISSUE TITLE
Outdated pinned color

### ISSUE THREAD

**Issue by mkozjak** [buo/homebrew-cask-upgrade#239]
Is there a way to set a different color for when the app is outdated but pinned?

Here's what I see now:
<img width="527" alt="270958059-6d6ce58c-5689-46d0-80b1-80ebd7992638" src="https://github.com/buo/homebrew-cask-upgrade/assets/3506172/1534a41b-5d5b-44aa-97ea-e02e2dfdf26e">

So, for example, it'd be great to have `bettertouchtool` in a different color, but `bluos-controller` in current color, as shown in the picture above.

Thanks!

**Comment by ondrejfuhrer** [comment]
If the question is around user-defined colours, no that's not possible, however implementing it shouldn't be a big deal. Contributions are welcomed.
