### ISSUE TITLE
Error: Cask 'omnigraffle' is unreadable: uninitialized constant Livecheck::Formula

### ISSUE THREAD

**Issue by skull-squadron** [buo/homebrew-cask-upgrade#242]
cu: e1aadd4c97203c0de552f0c0e00baee47604e2c7

brew: a4b4b9094054de3f2c93ad40814b51031949ab6e

`brew cu pin omnigraffle` against `{{HOMEBREW}}/Library/Taps/homebrew/homebrew-cask/Casks/o/omnigraffle.rb`

All casks are currently unpinnable.

**Comment by ondrejfuhrer** [comment]
I assume this was a temporary issue as it works fine for me.

```
~ ❯ brew cu unpin skype
Unpinned: skype
~ ❯ brew cu pin skype
Pinned: skype in version 8.107.0.215
```

In case it's still broken, let us know here.
