### ISSUE TITLE
run cask cu as super user

### ISSUE THREAD

**Issue by axot** [buo/homebrew-cask-upgrade#26]
I want add a cron job for automatic brew cask upgrade, something like virtualbox need super user privilege for installation. Does this possible achievable?

**Comment by adidalal** [comment]
(Homebrew Cask maintainer here)
No, don't do this.

Pass in sudo and renew it before installing pkg-based apps.
ie. https://github.com/vitorgalvao/dotfiles/blob/master/scripts/00_setup.sh#L5 and https://github.com/vitorgalvao/dotfiles/blob/master/scripts/02_apps.sh#L23

**Comment by robrecord** [comment]
Now found at https://github.com/vitorgalvao/dotfiles/blob/master/scripts/helper_functions.sh and https://github.com/vitorgalvao/dotfiles/blob/master/scripts/apps.sh
