### ISSUE TITLE
Application is `latest but forced to upgrade`

### ISSUE THREAD

**Issue by asteinbr** [buo/homebrew-cask-upgrade#27]
When I run `brew cu --dry-run` the application `teamviewer` for example is `up to date`. However, when I run the command `brew cu --all` then `teamviewer` is no longer `up to date`, it is instead `latest but forced to upgrade` and the application will be reinstalled (same version).

How can I avoid the the forced upgrade?

**Comment by buo** [comment]
Basically, `brew cu` will upgrade **all** outdated apps except the ones marked as latest. If you want to upgrade all outdated apps **including** the ones marked as latest but not the same version, there is no such thing.
