### ISSUE TITLE
name of brew update command

### ISSUE THREAD

**Issue by hao-lh** [buo/homebrew-cask-upgrade#30]
Hi buo,

One issue with name of brew command:
brew and brew cask are actually two repositories, mainly the previous is responsible for CLI, while the latter for GUI, thus `brew update` conflicts to the previous one, and to avoid this, I recommend use a new one or just the command in bin directory.

Another issue is with hint displayed while typing in the terminal, which is awesome, I was wondering which terminal you are using and if you can share the configuration files with us?

Many thanks and happy new year!
Hal,

**Comment by buo** [comment]
> One issue with name of brew command:
brew and brew cask are actually two repositories, mainly the previous is responsible for CLI, while the latter for GUI, thus brew update conflicts to the previous one, and to avoid this, I recommend use a new one or just the command in bin directory.

This tool uses `brew cu`, and `brew update` is a Homebrew's command, so it's not something we can handle.

> Another issue is with hint displayed while typing in the terminal, which is awesome, I was wondering which terminal you are using and if you can share the configuration files with us?

I'm using the [Fish](http://fishshell.com) shell with zero configuration.
