### ISSUE TITLE
Enhancement: Provide automated cleanup script

### ISSUE THREAD

**Issue by hiramknick** [buo/homebrew-cask-upgrade#35]
Great improvement on brew cask.  I've been looking for an easy way to maintain cask modules.

One suggestion, give me a command-line option to run "brew cask cleanup" automatically after the "brew cu" run is complete.

Thanks!

**Comment by JanSuchanek** [comment]
+ brew cleanup

**Comment by adidalal** [comment]
I use an alias: 
`alias brewup="brew update; brew cu; brew cleanup"`

FYI `brew cask cleanup` is an alias for `brew cleanup`

**Comment by z0rc** [comment]
> FYI `brew cask cleanup` is an alias for `brew cleanup`

[It is not](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb). `brew cask cleanup` clears cached downloads of installers used by cask that are left by `brew cleanup`.

**Comment by buo** [comment]
I opened a new PR which adds `--cleanup` option to clean up cached downloads after updating (i.e. `brew cask cleanup`), but it won't run `brew cleanup`.

`brew cleanup` cleans up the homebrew-core cache. `brew cu` (or homebrew-cask) has nothing to do with it and is not responsible for it.
