### ISSUE TITLE
brew cu should show current installed version

### ISSUE THREAD

**Issue by muescha** [buo/homebrew-cask-upgrade#39]
`brew cu --dry-run --cask postman` should show also the current installed version:

`Postman (postman): ==> v4.10.2 up to date`

**Comment by buo** [comment]
This issue was resolved by commit [3fb69e7](https://github.com/buo/homebrew-cask-upgrade/commit/3fb69e7cb87db97b86043917a0a22dd6bd2c3f06).

**Comment by muescha** [comment]
wow - nice table :)

👍

**Comment by muescha** [comment]
did you use the current version from local cask?

if i look for `kMDItemVersion` then i got this:

```
==> Found outdated apps
================================================================
No.  Name             Cask             Current  Latest  State     
================================================================
1/8  Github Atom      atom             1.11.2   1.15.0  outdated 

[...]

$ mdls -name kMDItemVersion /Applications/Atom.app
kMDItemVersion = "1.15.0"

```

**Comment by gastonmorixe** [comment]
@muescha I created a personal script to try to compare them towards the real installed version exactly like you mentioned using macOS `mdls`. It's not bullet-proof but it helps.

https://gist.github.com/gastonmorixe/9d3b9d6588442313272c11061f702a6e

<img width="798" alt="Image" src="https://github.com/user-attachments/assets/20fb75c4-f34d-44d8-a77f-7fa4e167fd7b" />
