### ISSUE TITLE
Manually upgraded apps are still shown as outdated

### ISSUE THREAD

**Issue by xliiauo** [buo/homebrew-cask-upgrade#40]
If I upgrade an app within the app and when I run `brew cu`, I will still see the app as outdated.

**Comment by buo** [comment]
This tool is totally dependent on cask files, so if you still see the app as outdated even after `brew update && brew cu`, there is no way to solve the problem. We just have to wait until the cask is updated.

**Comment by xliiauo** [comment]
Sorry for my misleading. I mean, say in Evernote, when I click `Check for updates` within Evernote and update there instead of running `brew update && brew cu` in the command line. When the update finishes, and if I run `brew update && brew cu` now, the 'brew cu' will still tell me that my Evernote is outdated and ask me to update. Is there any chance that this could be fixed?

**Comment by buo** [comment]
Manually updating an app outside HBC environment doesn't affect the metadata in caskroom, so we cannot retrieve the newly installed version and it will always be marked as `outdated`. This is also related to the casks having `auto-updates` stanza. PR #33 fixes the problem by just ignoring the auto-updates casks such as Evernote. The PR will be merged soon after some changes.

**Comment by xliiauo** [comment]
cool, thanks.

**Comment by buo** [comment]
This issue was resolved in PR #49.
