### ISSUE TITLE
No regular output from command

### ISSUE THREAD

**Issue by ucayalifish** [buo/homebrew-cask-upgrade#41]
Hi,
I'm using homebrew-cask-upgrade for pretty long time with great satisfaction. Unfortunately, suddenly the `brew cu` stops working as expected. Normally, the command outputs current state for all casks but now the output is empty. I would appreciate any suggestions for debugging the problem as I'm not a ruby developer at all.

TIA

Sergey

**Comment by buo** [comment]
homebrew-cask-upgrade doesn't give any output when it couldn't find any installed apps on your machine. Could you try it again after installing some apps?
