### ISSUE TITLE
private method `load' called for Hbc:Module

### ISSUE THREAD

**Issue by shendanpuff** [buo/homebrew-cask-upgrade#43]
Error: private method `load' called for Hbc:Module
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:38:in `block in each_installed'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:36:in `each'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:36:in `each_with_index'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:36:in `each_installed'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:10:in `outdated'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:50:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:10:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in `<main>'

**Comment by forrestwparker** [comment]
To add to this, I have no problem running `brew cu` on macOS 10.12.3, but I get the above error when I attempt to run the command on OSX 10.11.6.

**Comment by SainteCelery** [comment]
I get the same error as in the OP on 10.12.3

**Comment by ycaille** [comment]
Same error on macOS 10.12.3
I'm quite puzzled as I'm using `rbenv` with `ruby 2.4.0` set as `[global]` but error message keeps referring to `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55`

**Comment by scottsideleau** [comment]
Same error as OP.  System info:

MacOS 10.11.6
Homebrew 1.1.11-108-g09a926f44
Homebrew/homebrew-core (git revision d9798; last commit 2017-03-18)
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]

**Comment by yurikoles** [comment]
Another one affected here.

**Comment by krismorf** [comment]
After a clean mac install it works again for me

**Comment by buo** [comment]
It seems that this issue occurs in a specific environment. I couldn't reproduce this error on my mac 10.12.3 and 10.11.6, and it works well on [Travis CI](https://travis-ci.org/buo/homebrew-cask-upgrade).

**Comment by buo** [comment]
I could reproduce this error on the Homebrew master branch. The error was caused by [this commit](https://github.com/Homebrew/brew/commit/ed10135da4fbabca2798afe949b6f5af9544ec9f)  which is not yet released, so I think it's not a good idea to merge #44 now because it produces an error on the stable version.

**Comment by yurikoles** [comment]
@buo I don't see stable branch in brew, just master one. What kind of release we need to wait to?

**Comment by z0rc** [comment]
I'm pretty sure there is a big number of users on master branch of Homebrew. I'm not sure when and what was changed, but my installation tracks master branch of Homebrew, not the releases. And I really don't know how and whether I actually should switch from master branch to point releases.

**Comment by yurikoles** [comment]
```
/usr/local/Homebrew $ git branch -av 
* master                00af5250 caveats: combine completion and function messages
  remotes/origin/master 00af5250 caveats: combine completion and function messages
```

https://github.com/Homebrew/install/blob/master/install#L305
in install script
```
system git, "reset", "--hard", "origin/master"
```

**Comment by buo** [comment]
I added a hack to fix this issue temporarily. The hack will be removed in the future when [Homebrew 1.1.12](https://github.com/Homebrew/brew/releases/tag/1.1.12) is released.

**Comment by yurikoles** [comment]
Error has just returned today.

**Comment by buo** [comment]
I don't see any errors on the stable branch (git revision 394f9fa0):

```
$ git checkout stable
$ brew -v
Homebrew 1.1.11
Homebrew/homebrew-core (git revision cc8ae; last commit 2017-03-23)
```
and master branch (git revision 17cc40f1):

```
$ git checkout master
$ brew -v
Homebrew 1.1.11-132-g17cc40f1
Homebrew/homebrew-core (git revision cc8ae; last commit 2017-03-23)
```

**Comment by yurikoles** [comment]
```
$ brew -v
Homebrew 1.1.11-3388-gf8cf5066
Homebrew/homebrew-core (git revision 328a89; last commit 2017-03-23)
```

**Comment by yurikoles** [comment]
@buo sorry, seems like I have something wrong with my master branch of cask. I have recreated master and now this issue is fixed.
