### ISSUE TITLE
add `brew cu help` and `brew cu --help`

### ISSUE THREAD

**Issue by muescha** [buo/homebrew-cask-upgrade#50]
please add:

[ ] `brew cu help`
[ ] `brew cu --help`

that are the first commands i tried

**Comment by buo** [comment]
We cannot use `brew cu --help` because Homebrew hijacks `--help` option and shows its banner,  I think it's a Homebrew's bug and should be fixed.

**Comment by muescha** [comment]
filed an issus at `brew`

**Comment by buo** [comment]
I opened a new pull request on Homebrew. See Homebrew/brew#2391. I hope they apply it.
