### ISSUE TITLE
The output information is not formated well

### ISSUE THREAD

**Issue by liziqiang** [buo/homebrew-cask-upgrade#51]
Please see the attachment.
When the app name is too long, the output is not so good. eg:java
![qq20170326-093628 2x](https://cloud.githubusercontent.com/assets/208130/24327611/1dc50bf0-1208-11e7-9edb-d218f3f68c7e.jpg)

**Comment by krismorf** [comment]
I also believe that the new output holds too much information. (People use `homebrew-cask-upgrade` to find outdated apps, in the first place, and not to get a list of all their apps, even though the feature is pretty neat)

`brew cu` could only list the outdated apps and prompt you to update
`brew cu --full` could show the current output

This way brew cu behaves as a 'Check for updates'

**Comment by monouser7dig** [comment]
The older output worked much better on smaller terminal windows as well 

The new one is quite clunky 

I'd personally much preferred the old one for that reason.

**Comment by jrking123** [comment]
I'll third that. Before, I was getting beautiful color-coded concise info. This feels like a trip back to the 90's (or 80's) :-)

**Comment by qkdreyer** [comment]
Any status update ? @buo

**Comment by buo** [comment]
I thought table formatting was better because there were too many things to display (no., app name, cask name, current version, latest version, auto-update, state), but I was wrong. I'm thinking of going back to the previous color-coded concise info after reducing the number of columns or resizing the long strings like JDK versions. Thank you for your suggestions.

**Comment by jrking123** [comment]
@buo - kudos on the beautiful new update output!
One column size issue and a feature request:
- Could the **Current** & **Latest** columns be made wide enough to display all but the craziest (Java...) version numbers?
- Could we have an option to only list the updates made (`--quiet`)? 

Continuing _thanks_!
<img width="962" alt="screen shot 2017-08-07 at 13 08 10" src="https://user-images.githubusercontent.com/3474104/29037631-62c70d2e-7b72-11e7-87f3-3a152ebeb79f.png">
