### ISSUE TITLE
missing option to force upgrade only apps that auto-update

### ISSUE THREAD

**Issue by stangri** [buo/homebrew-cask-upgrade#54]
First of all, thank you so much for your work on creating and maintaining the proper CLI package manager for macOS!

To the issue -- right now the ```-a``` option force-upgrades "latest" apps as well as those that auto-update without the recourse to force upgrade only "ignored" apps which auto-update themselves. I personally have a whole bunch of those "latest" apps and it seems wasteful to force-upgrade them when all I want to do is upgrade the outdated apps.

The whole reason I'm using the separate package manager is that I want an ability to update all my outdated apps in one go rather than to rely on apps' built-in auto-update feature. I would suggest to stop ignoring (and not updating thru cask-upgrade) apps that have auto-update built-in.

If that doesn't align with your view, please give us an option of force-upgrading only outdated ignored apps, without force-upgrading latest apps as well.

Thanks again!

**Comment by buo** [comment]
This issue was fixed in PR #53.
