### ISSUE TITLE
Use reinstall instead of just overwriting apps

### ISSUE THREAD

**Issue by phdoerfler** [buo/homebrew-cask-upgrade#57]
I got this warning while upgrading using `brew cu -a`:

```Warning: It seems there is already an App at '/Applications/IntelliJ IDEA.app'; overwriting.```

I assume that `homebrew-cask-upgrade` issues `brew cask install --force` instead of `brew cask reinstall`. Would it hurt to use `reinstall` instead? I'd strongly assume this would get rid of the warning.

**Comment by buo** [comment]
`reinstall` produces an error and stops:

```
$ brew cask reinstall evernote
==> Downloading https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_6.11_454874.dmg
Already downloaded: /Users/tony/Library/Caches/Homebrew/Cask/evernote--6.11_454874.dmg
==> Verifying checksum for Cask evernote
Error: It seems there is already an App at '/Applications/Evernote.app'.
```

`reinstall --force` works well, but it still shows an warning:

```
$ brew cask reinstall evernote --force
==> Downloading https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_6.11_454874.dmg
Already downloaded: /Users/tony/Library/Caches/Homebrew/Cask/evernote--6.11_454874.dmg
==> Verifying checksum for Cask evernote
Warning: It seems there is already an App at '/Applications/Evernote.app'; overwriting.
==> Removing App '/Applications/Evernote.app'.
==> Moving App 'Evernote.app' to '/Applications/Evernote.app'.
🍺  evernote was successfully installed!
```

So, using `reinstall` isn't helpful to get rid of the warning.

**Comment by phdoerfler** [comment]
That is odd. `reinstall` works for me. That's how I updated my casks before I found this neat tool:

```brew cask outdated | xargs brew reinstall```

**Comment by buo** [comment]
Oh, it works well on my other mac. I will investigate further.

**Comment by syd3n** [comment]
**_This issue seems to be occurring very frequently for me._**

#### Command I am issuing to upgrade:
`brew cu --verbose --cleanup --interactive --all --force;`

#### Sample of errors I see during the upgrade (happens for multiple apps being upgraded):
```
==> Installing Cask steam
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/xxxx.dmg
mkbom -s -i /var/folders/xxxx.list -- /var/folders/xxxx.bom
ditto --bom /var/folders/xxxx.bom -- /private/var/folders/xxxx
diskutil eject /private/var/folders/xxxx
cp -pR /var/folders/xxxx/Steam.app/. /usr/local/Caskroom/steam/latest/Steam.app
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/MacOS/public with non-directory /var/folders/xxxx/Steam.app/./Contents/MacOS/public
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/Frameworks/Breakpad.framework/Resources with non-directory /var/folders/xxxx/Steam.app/./Contents/Frameworks/Breakpad.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/Frameworks/Breakpad.framework/Versions/Current with non-directory /var/folders/xxxx/Steam.app/./Contents/Frameworks/Breakpad.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/Frameworks/Breakpad.framework/Headers with non-directory /var/folders/xxxx/Steam.app/./Contents/Frameworks/Breakpad.framework/Headers
==> Purging files for version latest of Cask steam
Error: Failure while executing; `cp -pR /var/folders/xxxx/Steam.app/. /usr/local/Caskroom/steam/latest/Steam.app` exited with 1. Here's the output:
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/MacOS/public with non-directory /var/folders/xxxx/Steam.app/./Contents/MacOS/public
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/Frameworks/Breakpad.framework/Resources with non-directory /var/folders/xxxx/Steam.app/./Contents/Frameworks/Breakpad.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/Frameworks/Breakpad.framework/Versions/Current with non-directory /var/folders/xxxx/Steam.app/./Contents/Frameworks/Breakpad.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/steam/latest/Steam.app/./Contents/Frameworks/Breakpad.framework/Headers with non-directory /var/folders/xxxx/Steam.app/./Contents/Frameworks/Breakpad.framework/Headers
```

#### Workaround solution:
 I've been resorting to interactively saying 'no' to the detected upgrades and then manually issuing brew reinstall for them.
`brew cask reinstall steam`

**Comment by yurikoles** [comment]
I can confirm this issue with `latest` version of casks.

**Comment by syd3n** [comment]
Here's a solution that works with the base brew-cask command:

`brew cask upgrade --greedy`

**Comment by ondrejfuhrer** [comment]
Hello there, since https://github.com/buo/homebrew-cask-upgrade/pull/172 we're using reinstall 🎉

**Comment by canondin** [comment]
> Hello there, since #172 we're using reinstall 🎉

I have the same question. See the picture below.
![image](https://user-images.githubusercontent.com/14855855/104276127-38a96d80-54df-11eb-8b24-f7ff9e453b57.png)

**Comment by ondrejfuhrer** [comment]
> I have the same question. See the picture below.

Hey @canondin, if it doesn't work with `brew cask reinstall` (or `brew reinstall --cask`), there is not much we can do here. My suggestion would be to reinstall the app manually by using `uninstall` and then `install`, possible removing the installed app from the `/Application` folder if it is still present there in between the steps.

**Comment by canondin** [comment]
> > I have the same question. See the picture below.
> 
> Hey @canondin, if it doesn't work with `brew cask reinstall` (or `brew reinstall --cask`), there is not much we can do here. My suggestion would be to reinstall the app manually by using `uninstall` and then `install`, possible removing the installed app from the `/Application` folder if it is still present there in between the steps.

Thank you,it works.

**Comment by MaximAndreevich** [comment]
Just faced the same issue. ```reinstall --force``` helped me. Thanks!
