### ISSUE TITLE
brew cu state ignored

### ISSUE THREAD

**Issue by alphatea** [buo/homebrew-cask-upgrade#60]
<img width="625" alt="qq20170520-234759 2x" src="https://cloud.githubusercontent.com/assets/27395080/26277273/e781f32e-3db7-11e7-91cf-f971904cb661.png">

I want upgrade pycharm， but the state [ignored].....

**Comment by azizuysal** [comment]
Same problem with other apps too. What is ignored state and why are some apps marked as ignored?

**Comment by tsilcher** [comment]
+1 Same issue here. I have to do a manual "brew cask reinstall" to update these casks marked as ignored.

**Comment by azizuysal** [comment]
This is what I use as a workaround (in [fish](https://fishshell.com) shell):
```sh
for app in (brew cask outdated --greedy)
    brew cask install --force $app
end
```

**Comment by a-omsk** [comment]
another solution
```
brew cask outdated --greedy | xargs brew cask install --force
```

**Comment by filippo-liverani** [comment]
I think auto-updating apps are marked `ignored` by default, you can pass `-a` option (`Include apps that auto-update in the upgrade`) to force the upgrade.
