### ISSUE TITLE
issue uninstalling Android Studio

### ISSUE THREAD

**Issue by disrupted** [buo/homebrew-cask-upgrade#65]
```bash
❯ brew cask uninstall android-studio-canary
==> Uninstalling Cask android-studio-canary
==> Removing App '/Applications/Android Studio 3.0 Preview.app'.
```

I have already uninstalled android-studio-canary as seen above (even trashed all of its files using AppCleaner). However every time I run `brew cu --yes --cleanup` from my alias a reinstallation is initiated. anyone know how to remove it once and for all?

**Comment by buo** [comment]
1. `brew cask uninstall -f android-studio-canary`
2. Go to `/usr/local/Caskroom`
3. Delete `android-studio-canary` directory if it exists

**Comment by disrupted** [comment]
thanks, issue can be closed.
