### ISSUE TITLE
Warning: Calling Hbc::DSL#license is deprecated!

### ISSUE THREAD

**Issue by docgyneco69** [buo/homebrew-cask-upgrade#66]
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

**Comment by buo** [comment]
It seems like you need to run `brew upgrade`. Please refer to #20.

**Comment by frankea** [comment]
Having the same issue, when running
`brew update && brew upgrade && brew cu`

`admins-iMac-7:~ afranke$ brew upgrade
admins-iMac-7:~ afranke$ brew cu
==> Options
Include auto-update (-a): false
Include latest (-f): false

==> Finding outdated apps
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!`

**Comment by corporate-gadfly** [comment]
In my case it was an outdated cask which had the deprecated syntax. See https://github.com/buo/homebrew-cask-upgrade/issues/77#issuecomment-350328134.
