### ISSUE TITLE
Where do we pick up the colors

### ISSUE THREAD

**Issue by pquodling** [buo/homebrew-cask-upgrade#70]
The video/image demoing this uses a range of colours in the text - I just installed and it's all monochrome - where do we pick that colorization up from...

**Comment by buo** [comment]
It seems like your terminal is not capable of printing ANSI colors. Could you run this command in your terminal?

```sh
echo $TERM
echo -e "\e[31mThis should be red\e[0m"
```

**Comment by pquodling** [comment]
echo $TERM
echo $TERM_PROGRAM
echo -e "\e[31mThis should be red\e[0m"
screen
iTerm.app
This should be red

**Comment by ondrejfuhrer** [comment]
@pquodling Since you are using iTerm, can you check what you have set as `Report Terminal Type`? You can find it under `Preferences` -> `Profiles` -> your profile (or `Default`) -> `Terminal` tab.
