### ISSUE TITLE
Is this what is meant to happen?

### ISSUE THREAD

**Issue by pquodling** [buo/homebrew-cask-upgrade#71]
I installed this and ran it with the brew cu -facy command line. 

It goes through a whole much of stuff, about installs. About ten things to be installed - it appears to do that... 

Just to be sure, I issue the command again - it should (in theory) come back with "nothing to update" or similar. Nope, it goes through and downloads and installs them all again.  

Here is the tail end of what happens - and it will keep happening, as if nothing has been updated. Huh?

**Comment by pquodling** [comment]
treesheets was successfully installed!
==> Upgrading viber to latest
==> Satisfying dependencies
==> Downloading https://download.viber.com/desktop/mac/Viber.dmg
######################################################################## 100.0%
==> No checksum defined for Cask viber, skipping verification
==> Installing Cask viber
Warning: It seems there is already an App at '/Applications/Viber.app'; overwriting.
==> Removing App '/Applications/Viber.app'.
==> Moving App 'Viber.app' to '/Applications/Viber.app'.
🍺  viber was successfully installed!
==> Upgrading window-wrangler to latest
==> Satisfying dependencies
==> Downloading http://mindflow.dk/software/windowwrangler/windowwrangler.dmg

curl: (7) Failed to connect to mindflow.dk port 80: Operation timed out
Error: Download failed on Cask 'window-wrangler' with message: Download failed: http://mindflow.dk/software/windowwrangler/windowwrangler.dmg
Error: Install incomplete.
==> Upgrading wireframe-sketcher to latest
==> Satisfying dependencies
==> Downloading http://wireframesketcher.com/downloads/WireframeSketcher-latest-macosx.zip
######################################################################## 100.0%
==> No checksum defined for Cask wireframe-sketcher, skipping verification
==> Installing Cask wireframe-sketcher
Warning: It seems there is already an App at '/Applications/WireframeSketcher.app'; overwriting.
==> Removing App '/Applications/WireframeSketcher.app'.
==> Moving App 'WireframeSketcher.app' to '/Applications/WireframeSketcher.app'.
🍺  wireframe-sketcher was successfully installed!
==> Removing cached downloads
/Users/peter/Library/Caches/Homebrew/Cask/dropbox--latest
/Users/peter/Library/Caches/Homebrew/Cask/etrecheck--latest.zip
/Users/peter/Library/Caches/Homebrew/Cask/google-chrome--latest.dmg
/Users/peter/Library/Caches/Homebrew/Cask/infinit--latest.dmg
/Users/peter/Library/Caches/Homebrew/Cask/joinme--latest.aspx
/Users/peter/Library/Caches/Homebrew/Cask/ltspice--latest.dmg
/Users/peter/Library/Caches/Homebrew/Cask/treesheets--latest.zip
/Users/peter/Library/Caches/Homebrew/Cask/viber--latest.dmg
/Users/peter/Library/Caches/Homebrew/Cask/wireframe-sketcher--latest.zip
==> This operation has freed approximately 441.2MB of disk space.

**Comment by buo** [comment]
Yes, it's normal, and it's because of `-facy` options:

- `-f`: Include apps that are marked as latest.
- `-a`: Include apps that auto-update in the upgrade.
- `-c`: Cleans up cached downloads and tracker symlinks after updating.
- `-y`: Update all outdated apps; answer yes to updating packages.

So the apps marked as latest will be updated(re-installed) again and again whenever you run the command.

**Comment by pquodling** [comment]
So, in order to just upgrade what needs to be updated (i.e. what is out of date), I just  do a brew cu -y or possibly a -cy?

**Comment by buo** [comment]
@pquodling yes, you are right.
