### ISSUE TITLE
How is homebrew-cask-upgrade updated?

### ISSUE THREAD

**Issue by winterflags** [buo/homebrew-cask-upgrade#73]
I am not very familiar with brew taps. Is there any need to update `homebrew-cask-upgrade` *itself*? If so, how is that done?

**Comment by buo** [comment]
You don't need to update `homebrew-cask-upgrade` by yourself. If you update Homebrew using `brew update`, it will update all brew taps too. You can check the log message.

```console
$ brew update
Updated Homebrew from 914378cf2 to 455ec4c9b.
Updated 3 taps (buo/cask-upgrade, caskroom/cask, homebrew/core).
...
```
