### ISSUE TITLE
Allow for quieter operation

### ISSUE THREAD

**Issue by rjstanford** [buo/homebrew-cask-upgrade#75]
It would be great to have a flag that didn't output anything in the case where no outdated apps were found (specifically, no apps that would show up in a "Found outdated apps" list).  In normal operation this would then behave similarly to "brew upgrade".

Hiding output is easy, but I wouldn't want to hide actual useful (read: unexpected) output, and it doesn't seem to have a good way of differentiating between the two.

**Comment by rjstanford** [comment]
Great tool though - amazingly useful.

**Comment by jrking123** [comment]
I'll second this. The "all installed list" is beautiful and would be nice to have available on demand, but just adds clutter in an update script output.
