### ISSUE TITLE
# Question: Why arent some apps upgraded?

### ISSUE THREAD

**Issue by hugeme** [buo/homebrew-cask-upgrade#79]
Thx for providing such an easy way to upgrade casks. However, for some apps Im not fully understand the behaviour and how to adjust it:

                                ==> Finding outdated apps
                       Cask                Current                                 Latest                                  A/U    Result
                 1/25  alfred              3.2_759                                 3.4.1_860                                Y   [  PASS  ]
                 2/25  atom                1.12.6                                  1.19.7                                   Y   [  PASS  ]
                 3/25  caffeine            1.1.1                                   1.1.1                                        [   OK   ]
                 4/25  datagrip            2016.3                                  2017.2.2,172.4155.28                     Y   [  PASS  ]
                 5/25  firefox             50.0.2                                  55.0.3                                   Y   [  PASS  ]
                 6/25  flux                37.7                                    39.984                                   Y   [  PASS  ]
                 7/25  gimp                2.8.22                                  2.8.22                                       [   OK   ]
                 8/25  google-chrome       latest                                  latest                                   Y   [  PASS  ]
                 9/25  intellij-idea       2017.1,171.3780.107                     2017.2.3,172.3968.16                     Y   [  PASS  ]

                12/25  mactex              20161009,20170524                       20170524                                     [   OK   ]
                13/25  onyx                3.2.8,latest                            3.2.8                                        [   OK   ]
                14/25  pycharm             2016.3                                  2017.2.3,172.3968.37                     Y   [  PASS  ]
                15/25  rstudio             1.0.153                                 1.0.153                                      [   OK   ]
                16/25  skim                1.4.29                                  1.4.29                                       [   OK   ]
                19/25  slack               2.6.3                                   2.7.1                                    Y   [  PASS  ]
                20/25  spectacle           1.2                                     1.2                                      Y   [  PASS  ]
                21/25  spotify             latest                                  latest                                   Y   [  PASS  ]
                23/25  texmaker            5.0.2,latest                            5.0.2                                        [   OK   ]
                25/25  xquartz             2.7.11                                  2.7.11                                       [   OK   ]
                ==> Removing cached downloads
                Nothing to do

So after initially running cask upgrade, some of the apps have been upgraded and some not.
For instance, I have atom 1.19.3, the current state is 1.12.6 according to `homebrew-cask-upgrade` . So why is the `Current` wrong and why are some apps like `datagrip`for instance not updated. 
Thank you

**Comment by hautonjt** [comment]
Some apps have auto-update functionality, so they aren't upgraded by default. When these apps update by themselves, the version numbers become out of sync.

**Comment by ondrejfuhrer** [comment]
If you only upgrade them via brew script, just use `-a` that updates also the auto-update apps.

**Comment by pythoninthegrass** [comment]
Thanks for tha `-a` switch @ondrejfuhrer! That answers my question too!
