### ISSUE TITLE
brew cu --all Error: Unknown command: cu

### ISSUE THREAD

**Issue by ClashTheBunny** [buo/homebrew-cask-upgrade#82]
I have the repo tapped, but I'm not getting cu to work anymore.  Don't know when this happened, possibly within the last 24 hours, so around October 14.

**Comment by ondrejfuhrer** [comment]
Hello @ClashTheBunny , can you maybe post the result of `brew tap` command? Or possible `brew cask list` for example to see, if there are any errors maybe? 

Everything works fine for me, no issues.

**Comment by sildvauresberg** [comment]
Hello @ondrejfuhrer, I tried `brew cu -ay` and got the following message `Error: Unknown command: cu`

```
> brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
romkatv/powerlevel10k
```
```
> brew list --cask
font-hack-nerd-font
```
```
> brew --version
Homebrew 2.5.2
Homebrew/homebrew-core (git revision 8771da; last commit 2020-09-21)
Homebrew/homebrew-cask (git revision b0e8d; last commit 2020-09-21)
```

**Comment by ondrejfuhrer** [comment]
Hey @sildvauresberg ,
As you can see from the `brew tap` result, you don't have the repo "tapped". Please follow the [installation instructions](https://github.com/buo/homebrew-cask-upgrade#installation).
