### ISSUE TITLE
I keep getting an error  - how do I fix it... 

### ISSUE THREAD

**Issue by pquodling** [buo/homebrew-cask-upgrade#85]
==> Found outdated apps
     Cask                Current  Latest  A/U    Result
1/1  wireshark-chmodbpf           2.4.2        [OUTDATED]
==> Upgrading wireshark-chmodbpf to 2.4.2
Error: Cask 'wireshark-chmodbpf' conflicts with 'wireshark'.
Obelix:~ peter$
──────────────

**Comment by ondrejfuhrer** [comment]
Do you have also `wireshark` cask installed? Seems like you are trying to update a cask that conflicts with another one. In that case, I think the only solution is to use just one of those.
