### ISSUE TITLE
Warning: Calling "cask :v1 => 'token'" is deprecated!

### ISSUE THREAD

**Issue by gerrymiller** [buo/homebrew-cask-upgrade#87]
When running `brew cu --yes --cleanup` I get the following:

```
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:41:in `load_cask'
Please report this to the buo/cask-upgrade tap!
```

**Comment by ondrejfuhrer** [comment]
Hello @gerrymiller , the problem is, that you have outdated cask that uses old notation. Try running `brew update` before. If the problem persists, you have a cask that was not updated and was probably removed from the repository. 

You can find the outdated cask by running 
```bash
grep -r "cask :v1 =>" /usr/local/Homebrew/Library/Taps/*
```

**Comment by gerrymiller** [comment]
That's interesting, because I do call `brew update` before. In fact, the complete line I use to update my machine daily is:

```
brew update; brew upgrade; brew cleanup; brew prune; brew doctor; brew cu --yes --cleanup; apm update --no-confirm
```

`grep` was unable to find any outdated casks, as you suggested:

```
______________________________
| ~ @ Gerry's MacBook (gerry) 
| => grep -r "cask :v1 =>" /usr/local/Homebrew/Library/Taps/*

______________________________
| ~ @ Gerry's MacBook (gerry) 
| => 
```

Any other ideas? I'm also seeing the same issue reported in #66 

```
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:41:in `load_cask'
Please report this to the buo/cask-upgrade tap!
```

I validated this is not in any casks as well:

```
| ~ @ Gerry's MacBook (gerry) 
| => grep -r "Hbc::DSL#license" /usr/local/Homebrew/Library/Taps/*
______________________________
| ~ @ Gerry's MacBook (gerry) 
| => 
```

Any ideas? Thank you!

**Comment by ondrejfuhrer** [comment]
Hey @gerrymiller , sorry I didn't have much time to investigate that. If you are also getting the problem with `DSL#licence` there is definitely some outdated and not supported cask in your machine. 

My next step would be to just check, which cask is missing, so by running `brew cask list` you get all the casks, that are installed on your machine. Not sure how many taps you use (you can see them in `/usr/local/Homebrew/Library/Taps/caskroom/`), but i.e. if you go with `ls -la /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks` you will see all the official casks you that are there by default. 

My guess would be, that you have installed something that is not there any more.

**Comment by gerrymiller** [comment]
Thanks, @ondrejfuhrer. Here is what I get when I call `brew cask list`:

```
| ~ @ Gerry's MacBook (gerry) 
| => brew cask list
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:23:in `load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `block in load'

arduino                  electrum                 handbrake                jump-desktop             mysqlworkbench           sqlworkbenchj
dnscrypt                 gimp                     java                     keybase                  osxfuse                  tunnelblick
```

**Comment by ondrejfuhrer** [comment]
Hey @gerrymiller ,
I made a quick look and it seems there is no cask `jump-desktop` is not there any more, since it was renamed in https://github.com/caskroom/homebrew-cask/pull/39904 

Try uninstalling it (`brew cask uninstall jump-desktop`) and install again with the new name (`brew cask install jump`) to see if that helps. 

All the others should be fine.

**Comment by ondrejfuhrer** [comment]
@gerrymiller also one comment reminded me, where you can look. If you take a look here https://github.com/buo/homebrew-cask-upgrade/issues/77#issuecomment-350328134 the deprecated stuff will be located in `/usr/local/Caskroom/` so you can take a look there

```bash
grep -r "cask :v1 =>" /usr/local/Caskroom/*
```

**Comment by gerrymiller** [comment]
That did it, thank you! It was jump-desktop.
