### ISSUE TITLE
Calling Hbc::DSL#license is deprecated

### ISSUE THREAD

**Issue by jackfrys** [buo/homebrew-cask-upgrade#88]
Got this warning message today after `$ brew upgrade && brew cu -a`:

```Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:41:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:41:in `load_cask'
Please report this to the buo/cask-upgrade tap!```

**Comment by ondrejfuhrer** [comment]
Hello @jackfrys,

can you please try to go through your casks and find out, which one is causing that and see if it is still maintainable? In the other issues with deprecated features, you can see how to take a look.

**Comment by jackfrys** [comment]
@ondrejfuhrer Yep, I found the problem in one of my casks and reported it to the maintainers - thanks!

Do you suppose it's possible to modify the warning so it points users to the tap of the offending cask rather than here?

**Comment by ondrejfuhrer** [comment]
@jackfrys Thanks for the suggestion, I was already thinking about it, but didn't have time to look into it so far.

**Comment by ondrejfuhrer** [comment]
@jackfrys Hey, sorry for such a late response. I did took a look into that and it is not simple, since that is not "our" error message. It is generated by Homebrew itself and overriding that part would be a great hassle and probably not worth it.
