### ISSUE TITLE
Improvement: Blacklist not-to-be-updated software

### ISSUE THREAD

**Issue by derphilipp** [buo/homebrew-cask-upgrade#90]
It would be nice if one could set a certain software to be ignore with the updates;

I usually like to clean my software all up to date, but some software just can't be updated (plugins that depend on older versions, licensing reasons, etc.

**Comment by ondrejfuhrer** [comment]
Thanks for the suggestion, it appeared here already few times to not update casks, that are pinned. Unfortunately the `brew pin` does not work with casks so it would need to be implemented (or wait until someone implements it in the "cask team"). So far I guess no one had time to do that.
