### ISSUE TITLE
Exclude specific casks

### ISSUE THREAD

**Issue by exophunk** [buo/homebrew-cask-upgrade#93]
Hey, is it possible to add an option to exclude certain casks from upgrading?

Something like `--exclude [casknames]`

The microsoft-office cask upgrade always hangs on the installer and I can't find a way to fix ist. Therefore it would be nice to simply exclude it.

**Comment by ondrejfuhrer** [comment]
Hey @exophunk ,
Nice idea, should not be hard to implement and I think that would also solve some other issues. I wanted to look into that, but so far I didn't have time 😞

**Comment by paour** [comment]
I would suggest making it possible to "pin" or ignore casks, in a settings file. Some casks I never want to upgrade, and having to `--exclude` them on every run would be annoying.

**Comment by Mehran** [comment]
yes i want it also .
